### ISSUE TITLE
lack some parameters to run demo.py

### ISSUE THREAD

**Issue by Stack-Liu** [NVlabs/CenterPose#10]
Hi, thanks for your code. I encountered a problem when I try to run demo.py. I loaded the pre-trained parameters of 'chair' (chair_v1_140.pth), and used the images in the chair folder. But it prompted that some parameters were missing, as shown below. I would appreciate your help.

F4`)BX](https://user-images.githubusercontent.com/95119853/188465002-d4c4eecb-409f-4c25-bc42-8a40723d66af.png)

**Comment by NeilLHY** [comment]
It seems that the keys of the pretrained weights does not match the weights of the created model.

**Comment by Stack-Liu** [comment]
Sorry about that. I used 'DeformConv2dPack' in 'mmcv' to replace the original ‘DCNv2’ due to the failed compilation of it. That will  cause some problems.
