### ISSUE TITLE
Question about scale factor on translation vector

### ISSUE THREAD

**Issue by AlbertoRemus** [NVlabs/CenterPose#2]
Hello, thanks for this awesome work!

I have a question related to the **scale factor**: from your paper it's crystal clear to me that it's possible to recover just the **relative size** of the estimated 3D bounding box.

However I was wondering whether the translation vector of the 6D pose is estimated with absolute scale (provided the correct **intrinsic parameters**) or not

I remain at your disposal for further clarification about my question.

**Comment by nuaayxy** [comment]
its impossible to get absolute scale since its a monocular camera, you would need an IMU to get the real world scale. Objects can be bigger and far away or small and closer, however if you know an object which is fixed size, you might be able to use pnp to solve for the real scale, since we know the credit card size is fixed?

**Comment by Uio96** [comment]
> its impossible to get absolute scale since its a monocular camera, you would need an IMU to get the real world scale. Objects can be bigger and far away or small and closer, however if you know an object which is fixed size, you might be able to use pnp to solve for the real scale, since we know the credit card size is fixed?

Agreed. IMU is one of the solutions. We also mentioned some other ones in the arXiv paper https://arxiv.org/pdf/2109.06161.pdf.

> Previous work has explored different ways to obtain the scale factor, including manual measurement [40], [41], calculation based on normal vector of the table [15], pose fitting via depth alignment [6], and multi-view consistency [42].
